### ISSUE TITLE
Model Cannot Predict any Shirts (Class Id 0)

### ISSUE THREAD

**Issue by H-Shafiei** [KMnP/fashionpedia-api#2]
Hi. Thanks for your great job!

When I am trying to check your model with your baseline predictor it cannot detect any shirts. Maybe a problem with training phase?

Since TF object detection api requires 1-based indexing for labels I think the problem may be related to your label map being 0-indexed. [Check this out](https://github.com/tensorflow/models/issues/1906)

**Comment by KMnP** [comment]
Hi @H-Shafiei , Thanks for catching this issue!! We checked our previous model, it indeed treats shirts (class id == 0) as background. 

A new model ([R-101-FPN](https://s3.amazonaws.com/ifashionist-dataset/attributes-maskrcnn/r101-fpn.zip)) was uploaded with the fixed category id issue. We also updated the predictor demo.

This issue is closed with the updated model link. Let me know if there are any other issues!

**Comment by H-Shafiei** [comment]
Thanks for your quick fix. Is it possible to have your Attribute Mask RCNN model code?🤔

**Comment by KMnP** [comment]
Yes. We are preparing to opensource the Attribute Mask RCNN model source code. Please stay tuned!

**Comment by H-Shafiei** [comment]
Thanks! Sure ;)
